#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE)
case_lib <- Sys.getenv("LRRK2_R_LIB", unset = "")
if (nzchar(case_lib)) .libPaths(c(case_lib, .libPaths()))
suppressPackageStartupMessages({library(ggplot2);library(patchwork);library(data.table)})
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE); date<-"2026-08-01"; outdir<-file.path(root,"results/figures/supplementary/FigS_single_cell_input_QC"); dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
q<-fread(file.path(root,"results/statistics",paste0("single_cell_qc_sample_summary_",date,".csv"))); inc<-fread(file.path(root,"results/statistics",paste0("single_cell_qc_inclusion_summary_",date,".csv")))
pal<-c(GSE131928="#0072B2",GSE103224="#E69F00",GSE138794="#009E73")
p1<-ggplot(q,aes(median_detected_features,median_mitochondrial_percent,color=dataset,size=n_cells))+geom_point(alpha=.8)+scale_color_manual(values=pal)+scale_size_continuous(range=c(2,8))+scale_x_log10()+labs(x="Median detected features (log scale)",y="Median mitochondrial proportion (%)",color=NULL,size="Cells")+theme_classic(base_size=8)
p2<-ggplot(q,aes(reorder(paste(dataset,tumor_id,sep=":"),diagnostic_flag_fraction),diagnostic_flag_fraction,fill=dataset))+geom_col(width=.8)+geom_hline(yintercept=.2,linetype=2,color="#777777")+coord_flip()+scale_fill_manual(values=pal)+labs(x=NULL,y="QC diagnostic-flag fraction",fill=NULL)+theme_classic(base_size=7)+theme(legend.position="none",axis.text.y=element_text(size=4.5))
tot<-inc[,.(primary=sum(primary_cells),sensitivity=sum(qc_sensitivity_cells)),by=dataset]; z<-melt(tot,id.vars="dataset",variable.name="analysis",value.name="cells")
p3<-ggplot(z,aes(dataset,cells,fill=analysis))+geom_col(position=position_dodge(.75),width=.65)+scale_fill_manual(values=c(primary="#4D4D4D",sensitivity="#56B4E9"),labels=c("Primary: all submitter-filtered","QC sensitivity"))+labs(x=NULL,y="Cells",fill=NULL)+theme_classic(base_size=8)+theme(axis.text.x=element_text(angle=20,hjust=1),legend.position="top")
fig<-(p1|p3)/p2+plot_layout(heights=c(1,1.35),guides="collect")+plot_annotation(tag_levels="A",theme=theme(plot.tag=element_text(face="bold",size=9)))
stem<-file.path(outdir,paste0("FigS_single_cell_input_QC_",date)); ggsave(paste0(stem,".pdf"),fig,width=178,height=155,units="mm",device=cairo_pdf); ggsave(paste0(stem,".png"),fig,width=178,height=155,units="mm",dpi=600,bg="white",device=ragg::agg_png)
write.csv(data.frame(input_path=c("results/statistics/single_cell_qc_sample_summary_2026-08-01.csv","results/statistics/single_cell_qc_inclusion_summary_2026-08-01.csv")),file.path(root,"provenance/figure_input_manifests/FigS_single_cell_input_QC_inputs.csv"),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(root,"provenance/software_snapshots",paste0("single_cell_qc_figure_sessionInfo_",date,".txt")))
