#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE)
case_lib <- Sys.getenv("LRRK2_R_LIB", unset = "")
if (nzchar(case_lib)) .libPaths(c(case_lib, .libPaths()))
suppressPackageStartupMessages({library(data.table);library(ggplot2)})
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);date<-"2026-08-01";d<-fread(file.path(root,"results/statistics",paste0("single_cell_hallmark_lrrk2_patient_correlations_",date,".csv")))[final_annotation=="neoplastic-like"&cohort_stratum%in%c("GSE131928_adult","GSE103224","GSE138794_scRNA")]
d[,cohort:=factor(cohort_stratum,levels=c("GSE131928_adult","GSE103224","GSE138794_scRNA"),labels=c("GSE131928 adult","GSE103224","GSE138794 scRNA"))];d[,program:=gsub("_"," ",sub("^HALLMARK_","",term_id))];ord<-d[cohort_stratum=="GSE131928_adult"][order(spearman_rho)]$program;d[,program:=factor(program,levels=rev(ord))];d[,sig_size:=pmin(-log10(pmax(adjusted_p_value,1e-12)),6)]
p<-ggplot(d,aes(cohort,program))+geom_point(aes(fill=spearman_rho,size=sig_size),shape=21,color="black",stroke=.25)+scale_fill_gradient2(low="#3B4CC0",mid="#F7F7F7",high="#B40426",midpoint=0,limits=c(-1,1),name="Spearman rho")+scale_size_continuous(range=c(2,7),name=expression(-log[10](FDR)),breaks=c(0,1,2,4,6),labels=c("0","1","2","4","6+"))+labs(x=NULL,y=NULL,title="Patient-level LRRK2-program correlations in neoplastic-like cells",subtitle="All 16 prespecified Gate 2 Hallmark programs")+theme_minimal(base_size=8)+theme(panel.grid.minor=element_blank(),axis.text.y=element_text(size=6.5),axis.text.x=element_text(face="bold"),plot.title=element_text(face="bold",size=10),legend.position="right")
outdir<-file.path(root,"results/figures/main/Fig5_single_cell_Hallmark_LRRK2_correlations");dir.create(outdir,recursive=TRUE,showWarnings=FALSE);stem<-file.path(outdir,paste0("Fig5_single_cell_Hallmark_LRRK2_correlations_",date));ggsave(paste0(stem,".pdf"),p,width=178,height=125,units="mm",device=cairo_pdf);ggsave(paste0(stem,".png"),p,width=178,height=125,units="mm",dpi=600,bg="white",device=ragg::agg_png)
write.csv(data.frame(input_path="results/statistics/single_cell_hallmark_lrrk2_patient_correlations_2026-08-01.csv",annotation="neoplastic-like",programs=16),file.path(root,"provenance/figure_input_manifests/Fig5_single_cell_Hallmark_LRRK2_correlations_inputs.csv"),row.names=FALSE);writeLines(capture.output(sessionInfo()),file.path(root,"provenance/software_snapshots",paste0("single_cell_hallmark_figure_sessionInfo_",date,".txt")))
