#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE,scipen=999)
case_lib <- Sys.getenv("LRRK2_R_LIB", unset = "")
if (nzchar(case_lib)) .libPaths(c(case_lib, .libPaths()))
suppressPackageStartupMessages(library(data.table))
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);date<-"2026-08-01";stats<-file.path(root,"results/statistics")
drivers<-c("IDH1","IDH2","TP53","ATRX","CIC","FUBP1","EGFR","PTEN","NF1","PIK3CA","PIK3R1","PDGFRA","RB1")
nonsyn<-c("Missense_Mutation","Nonsense_Mutation","Frame_Shift_Del","Frame_Shift_Ins","Splice_Site","In_Frame_Del","In_Frame_Ins","Translation_Start_Site","Nonstop_Mutation","Start_Codon_Del","Start_Codon_Ins","Stop_Codon_Del","Stop_Codon_Ins")
sel<-fread(file.path(root,"data/interim/harmonized_metadata",paste0("tcga_cnv_mutation_file_selection_",date,".csv")))[modality=="mutation"]
events<-list();audit<-list()
for(i in seq_len(nrow(sel))){r<-sel[i];if(r$selection_status!="selected"){audit[[i]]<-data.table(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id,status="selection_unavailable",events=NA_integer_);next};p<-file.path(root,"data/raw/TCGA/mutation",r$project,r$file_id,r$file_name);if(!file.exists(p)){audit[[i]]<-data.table(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id,status="file_missing",events=NA_integer_);next};con<-gzfile(p,"rt");ln<-readLines(con,warn=FALSE);close(con);ln<-ln[!startsWith(ln,"#")];if(length(ln)<2){audit[[i]]<-data.table(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id,status="empty_maf",events=0L);next};x<-fread(text=paste(ln,collapse="\n"));need<-c("Hugo_Symbol","Variant_Classification","Chromosome","Start_Position","Reference_Allele","Tumor_Seq_Allele2");if(!all(need%in%names(x))){audit[[i]]<-data.table(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id,status="missing_required_columns",events=NA_integer_);next};x<-x[Variant_Classification%in%nonsyn];x[,`:=`(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id)];x<-unique(x,by=c("patient_id","Chromosome","Start_Position","Reference_Allele","Tumor_Seq_Allele2"));events[[length(events)+1]]<-x[,.(dataset_id,patient_id,file_id,Hugo_Symbol,Variant_Classification,Chromosome,Start_Position,Reference_Allele,Tumor_Seq_Allele2)];audit[[i]]<-data.table(dataset_id=r$dataset_id,patient_id=r$patient_id,file_id=r$file_id,status="parsed",events=nrow(x))}
ev<-rbindlist(events,fill=TRUE);au<-rbindlist(audit,fill=TRUE);fwrite(ev,file.path(stats,paste0("tcga_nonsynonymous_mutation_events_",date,".csv")));fwrite(au,file.path(stats,paste0("tcga_mutation_file_parse_audit_",date,".csv")))
patients<-sel[,.(dataset_id,patient_id,selection_status)];burden<-ev[,.(nonsynonymous_burden=.N),by=.(dataset_id,patient_id)];patients<-merge(patients,burden,by=c("dataset_id","patient_id"),all.x=TRUE);patients[selection_status=="selected"&is.na(nonsynonymous_burden),nonsynonymous_burden:=0L]
for(g in drivers){pos<-unique(ev[Hugo_Symbol==g,.(dataset_id,patient_id)]);patients[[paste0("mut_",g)]]<-paste(patients$dataset_id,patients$patient_id)%in%paste(pos$dataset_id,pos$patient_id)}
fwrite(patients,file.path(stats,paste0("tcga_driver_mutation_patient_status_",date,".csv")))
info<-fread(file.path(stats,paste0("lrrk2_transcriptome_analysis_samples_",date,".csv")))[analysis=="primary"&cohort=="TCGA"];lock<-fread(file.path(stats,paste0("bulk_sample_inclusion_lock_",date,".csv")))[dataset_id%in%c("TCGA_LGG","TCGA_GBM")];info<-merge(info,lock[,.(sample_id,dataset_id)],by="sample_id");d<-merge(info,patients[selection_status=="selected"],by=c("dataset_id","patient_id"));d[,rna_z_project:=as.numeric(scale(LRRK2_log2)),by=dataset_id];d[,log1p_burden:=log1p(nonsynonymous_burden)]
fit_term<-function(dd,term,type){vars<-c("rna_z_project",term,"age_scaled_centered","sex");dd<-dd[complete.cases(dd[,..vars])];if(nrow(dd)<50)return(NULL);if(type=="driver"){dd[[term]]<-as.integer(dd[[term]]);n1<-sum(dd[[term]]);n0<-nrow(dd)-n1;if(min(n1,n0)<10)return(NULL)};dd[,sex:=relevel(factor(sex),"Female")];fit<-lm(as.formula(paste("rna_z_project~",term,"+age_scaled_centered+sex")),dd);sm<-coef(summary(fit));if(!term%in%rownames(sm))return(NULL);b<-sm[term,1];se<-sm[term,2];data.table(n=nrow(dd),term=term,positive_n=if(type=="driver")sum(dd[[term]])else NA_integer_,beta=b,se=se,ci_low=b-1.96*se,ci_high=b+1.96*se,p_value=sm[term,4],r_squared=summary(fit)$r.squared,cook_over_4n=sum(cooks.distance(fit)>4/nrow(dd)))}
mods<-list();for(ds in c("TCGA_LGG","TCGA_GBM")){dd<-d[dataset_id==ds];for(g in drivers){z<-fit_term(dd,paste0("mut_",g),"driver");if(!is.null(z))mods[[length(mods)+1]]<-z[,`:=`(dataset_id=ds,analysis="driver")]};z<-fit_term(dd,"log1p_burden","burden");if(!is.null(z))mods[[length(mods)+1]]<-z[,`:=`(dataset_id=ds,analysis="burden")]}
models<-rbindlist(mods,fill=TRUE);models[analysis=="driver",adjusted_p_value:=p.adjust(p_value,"BH"),by=dataset_id];fwrite(models,file.path(stats,paste0("tcga_driver_mutation_lrrk2_expression_models_",date,".csv")));writeLines(capture.output(sessionInfo()),file.path(root,"provenance/software_snapshots",paste0("tcga_driver_mutation_sessionInfo_",date,".txt")));cat("Parsed nonsynonymous events:",nrow(ev),"\n")
