#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE)
case_lib <- Sys.getenv("LRRK2_R_LIB", unset = "")
if (nzchar(case_lib)) .libPaths(c(case_lib, .libPaths()))
suppressPackageStartupMessages({library(data.table);library(ggplot2);library(patchwork)})
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);date<-"2026-08-01";sd<-file.path(root,"results/statistics")
cn<-fread(file.path(sd,paste0("tcga_lrrk2_locus_cnv_expression_models_",date,".csv")))[model_type%in%c("primary","workflow_stratified")];cn[,label:=paste(ifelse(dataset_id=="TCGA_LGG","LGG","GBM"),workflow_stratum,sep=" | ")];cn[,label:=factor(label,levels=rev(label))]
mu<-fread(file.path(sd,paste0("tcga_driver_mutation_lrrk2_expression_models_",date,".csv")));drv<-mu[analysis=="driver"];drv[,gene:=sub("^mut_","",term)];drv[,label:=paste(ifelse(dataset_id=="TCGA_LGG","LGG","GBM"),gene,sep=" | ")];setorder(drv,dataset_id,beta);drv[,label:=factor(label,levels=rev(label))];bur<-mu[analysis=="burden"]
pal<-c(TCGA_LGG="#0072B2",TCGA_GBM="#D55E00");tt<-theme_classic(base_size=8)+theme(plot.title=element_text(face="bold",size=9),plot.tag=element_text(face="bold",size=10),legend.position="none")
p1<-ggplot(cn,aes(beta,label,color=dataset_id))+geom_vline(xintercept=0,linetype=2,color="grey55")+geom_errorbar(aes(xmin=ci_low,xmax=ci_high),width=0,orientation="y",color="grey35")+geom_point(size=2.3)+scale_color_manual(values=pal)+labs(x="Adjusted beta",y=NULL,title="LRRK2 locus CNV–RNA association")+tt
p2<-ggplot(drv,aes(beta,label,color=dataset_id))+geom_vline(xintercept=0,linetype=2,color="grey55")+geom_errorbar(aes(xmin=ci_low,xmax=ci_high),width=0,orientation="y",color="grey50",linewidth=.45)+geom_point(aes(fill=adjusted_p_value<.05),shape=21,size=2,stroke=.3)+scale_color_manual(values=pal)+scale_fill_manual(values=c(`TRUE`="black",`FALSE`="white"))+labs(x="Adjusted difference in LRRK2 RNA z-score",y=NULL,title="Prespecified driver-mutation background")+tt+theme(axis.text.y=element_text(size=6.5))
p3<-ggplot(bur,aes(ifelse(dataset_id=="TCGA_LGG","LGG","GBM"),beta,fill=dataset_id))+geom_hline(yintercept=0,linetype=2,color="grey55")+geom_errorbar(aes(ymin=ci_low,ymax=ci_high),width=.15,color="grey35")+geom_point(shape=21,size=2.7)+scale_fill_manual(values=pal)+labs(x=NULL,y="Adjusted beta",title="Nonsynonymous mutation burden")+tt
fig<-(p1|p3)/p2+plot_layout(heights=c(.8,1.4))+plot_annotation(tag_levels="a")
out<-file.path(root,"results/figures/main/Fig8_TCGA_LRRK2_multiomics_alternative_explanations");dir.create(out,recursive=TRUE,showWarnings=FALSE);stem<-file.path(out,paste0("Fig8_TCGA_LRRK2_multiomics_alternative_explanations_",date));ggsave(paste0(stem,".pdf"),fig,width=183,height=170,units="mm",device=cairo_pdf);ggsave(paste0(stem,".png"),fig,width=183,height=170,units="mm",dpi=600,bg="white",device=ragg::agg_png)
fwrite(data.table(input_path=c(paste0("results/statistics/tcga_lrrk2_locus_cnv_expression_models_",date,".csv"),paste0("results/statistics/tcga_driver_mutation_lrrk2_expression_models_",date,".csv")),panel=c("a","b-c")),file.path(root,"provenance/figure_input_manifests/Fig8_TCGA_LRRK2_multiomics_alternative_explanations_inputs.csv"));writeLines(capture.output(sessionInfo()),file.path(root,"provenance/software_snapshots",paste0("tcga_multiomics_figure_sessionInfo_",date,".txt")))
