#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE,scipen=999)
case_lib <- Sys.getenv("LRRK2_R_LIB", unset = "")
if (nzchar(case_lib)) .libPaths(c(case_lib, .libPaths()))
suppressPackageStartupMessages({library(data.table);library(ggplot2);library(patchwork)})
root<-normalizePath(getwd(),winslash="/",mustWork=TRUE);date<-"2026-08-06"
out<-file.path(root,"results/figures/v7_2/supplementary/FigS3_mito_lysosome_oxidative_state");dir.create(out,recursive=TRUE,showWarnings=FALSE)
ev<-fread(file.path(root,"results/statistics/v7_2_mito_lysosome_pathway_evidence_2026-08-06.csv"));ds<-fread(file.path(root,"results/statistics/v7_2_mito_lysosome_domain_summary_2026-08-06.csv"));m<-fread(file.path(root,"results/statistics/v7_2_mito_lysosome_association_models_2026-08-06.csv"))
cl<-c(TCGA="TCGA",CGGA_RNASEQ_693="CGGA-693",CGGA_RNASEQ_325="CGGA-325");cc<-c(TCGA="#0072B2","CGGA-693"="#D55E00","CGGA-325"="#009E73")

h<-ev[collection=="HALLMARK"&method=="GSEA"];h[,cohort_label:=factor(cl[cohort],levels=unname(cl))];h[,program:=factor(ifelse(grepl("OXIDATIVE",term_id),"OXPHOS","ROS pathway"),levels=c("OXPHOS","ROS pathway"))]
p1<-ggplot(h,aes(cohort_label,effect,color=cohort_label,shape=cohort_label))+geom_hline(yintercept=0,color="grey65",linewidth=.35)+geom_point(size=2.5)+facet_wrap(~program,nrow=1)+scale_color_manual(values=cc)+scale_shape_manual(values=c(16,17,15))+labs(x=NULL,y="GSEA normalized enrichment score",title="The direction emerged from the locked Hallmark screen")+theme_classic(base_size=8)+theme(legend.position="none",strip.background=element_blank(),strip.text=element_text(face="bold"),plot.title=element_text(face="bold",size=8),axis.text.x=element_text(angle=25,hjust=1,size=6.5))

ds[,domain_label:=factor(domain,levels=rev(c("OXPHOS_ROS","mitochondrial_energy","mitochondrial_quality_control","oxidative_stress","lysosome_autophagy")),labels=rev(c("Hallmark OXPHOS/ROS","Mitochondrial energy","Mitochondrial quality control","Oxidative stress","Lysosome/autophagy")))]
p2<-ggplot(ds,aes(significant_results,domain_label,fill=method))+geom_col(position=position_dodge(width=.7),width=.62)+scale_fill_manual(values=c(GSEA="#0072B2",CAMERA="#E69F00"))+labs(x="Significant cohort-term results (BH FDR <0.05)",y=NULL,fill=NULL,title="GO/Reactome convergence")+theme_classic(base_size=8)+theme(legend.position="bottom",plot.title=element_text(face="bold",size=8),axis.text.y=element_text(size=6.5))

forest<-m[outcome%in%c("OXPHOS_ROS_STATE","MITO_QC","LYSOSOME_AUTOPHAGY")];forest[,cohort_label:=factor(cl[cohort],levels=unname(cl))];forest[,outcome_label:=factor(outcome,levels=c("OXPHOS_ROS_STATE","MITO_QC","LYSOSOME_AUTOPHAGY"),labels=c("OXPHOS-ROS state","Mitochondrial quality control","Lysosome/autophagy"))]
p3<-ggplot(forest,aes(beta,cohort_label,color=cohort_label,shape=cohort_label))+geom_vline(xintercept=0,linetype=2,color="grey55",linewidth=.35)+geom_errorbar(aes(xmin=ci_low,xmax=ci_high),orientation="y",width=0,linewidth=.5)+geom_point(size=2)+facet_wrap(~outcome_label,ncol=1,scales="free_y")+scale_color_manual(values=cc)+scale_shape_manual(values=c(16,17,15))+labs(x="Adjusted beta per SD LRRK2 (HC3 95% CI)",y=NULL,title="Sample-level associations")+theme_classic(base_size=8)+theme(legend.position="none",strip.background=element_blank(),strip.text=element_text(face="bold",size=6.8),plot.title=element_text(face="bold",size=8))

flow<-data.table(x=1,y=c(4.55,3.65,2.75,1.85,.95),label=c("Unbiased Hallmark screen","OXPHOS/ROS replicated in CGGA","GO/Reactome convergence","Patient-level score tests","PD literature: context only"),type=c("data","data","data","data","context"));flow[,`:=`(xmin=.66,xmax=1.34,ymin=y-.25,ymax=y+.25)]
arrows<-data.table(x=1,xend=1,y=c(4.27,3.37,2.47,1.57),yend=c(3.93,3.03,2.13,1.23))
p4<-ggplot(flow,aes(x,y))+geom_segment(data=arrows,aes(x=x,y=y,xend=xend,yend=yend),inherit.aes=FALSE,arrow=arrow(length=unit(1.7,"mm")),color=c(rep("grey35",3),"grey50"),linetype=c(rep(1,3),2),linewidth=.5)+geom_rect(aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax,fill=type),color="grey20",linewidth=.28)+geom_text(aes(label=label),size=1.85)+scale_fill_manual(values=c(data="#D9EEF7",context="#F2F2F2"))+coord_cartesian(xlim=c(.55,1.45),ylim=c(.55,4.85),clip="off")+labs(title="Evidence order: glioma data first, PD context last")+theme_void(base_size=8)+theme(legend.position="none",plot.title=element_text(face="bold",size=8,margin=margin(b=2)),plot.margin=margin(t=1,r=4,b=2,l=4))

fig<-(p1|p2)/(p3|p4)+plot_layout(widths=c(1,1.12),heights=c(1,1.15))+plot_annotation(tag_levels="A",theme=theme(plot.tag=element_text(face="bold",size=9)))
base<-file.path(out,"FigS3_mito_lysosome_oxidative_state_2026-08-06");ggsave(paste0(base,".pdf"),fig,width=178,height=145,units="mm",device=cairo_pdf);ggsave(paste0(base,".png"),fig,width=178,height=145,units="mm",dpi=600,bg="white");ggsave(paste0(base,".svg"),fig,width=178,height=145,units="mm",device=grDevices::svg)
dir.create(file.path(root,"provenance/figure_input_manifests"),recursive=TRUE,showWarnings=FALSE);fwrite(data.table(input_path=c("results/statistics/v7_2_mito_lysosome_pathway_evidence_2026-08-06.csv","results/statistics/v7_2_mito_lysosome_domain_summary_2026-08-06.csv","results/statistics/v7_2_mito_lysosome_association_models_2026-08-06.csv"),role=c("frozen pathway-level evidence","domain convergence summary","sample-level adjusted associations"),width_mm=178,height_mm=145),file.path(root,"provenance/figure_input_manifests/FigS3_V7_2_mito_lysosome_inputs_2026-08-06.csv"));writeLines(c(capture.output(sessionInfo()),"","Figure owner: bio-data-visualization-multipanel-figures","Export helper: bio-reporting-figure-export","PDF cairo; PNG 600 dpi; SVG vector"),file.path(root,"provenance/software_snapshots/v7_2_mito_lysosome_figure_sessionInfo_2026-08-06.txt"));message("V7.2 FigS3 exported")
